"""
Lesson 15 — turn everything you measured into a customer sizing memo.

Reads results/*.csv from lessons 01–14, picks the latest numbers, applies them to a
customer scenario, and writes results/SIZING_MEMO.md: the document you'd send after
a discovery call, and the backbone of a 10-minute project walkthrough.

    python build_memo.py
    python build_memo.py --peak-concurrency 200 --tickets-per-month 5e6 --slo-ms 800

Every number is traceable to a CSV row, and anything missing is marked TODO rather
than invented. That habit matters more than the numbers.
"""
import argparse
import csv
import math
from pathlib import Path

from felab.results import RESULTS


def latest(name: str) -> list[dict]:
    p = RESULTS / f"{name}.csv"
    return list(csv.DictReader(p.open())) if p.exists() else []


def f(x, fmt="{:,.0f}", todo="TODO (run the lesson)"):
    try:
        return fmt.format(float(x))
    except (TypeError, ValueError):
        return todo


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--customer", default="Acme Cloud (support triage agent)")
    ap.add_argument("--peak-concurrency", type=int, default=120)
    ap.add_argument("--tickets-per-month", type=float, default=2e6)
    ap.add_argument("--slo-ms", type=float, default=1000, help="p95 TTFT target")
    ap.add_argument("--in-tokens", type=int, default=3200, help="avg prompt tokens per ticket (agent preamble + ticket)")
    ap.add_argument("--out-tokens", type=int, default=60)
    ap.add_argument("--serverless-in", type=float, default=0.07, help="$ per 1M input tokens — check pricing page")
    ap.add_argument("--serverless-out", type=float, default=0.30)
    ap.add_argument("--cached-discount", type=float, default=0.5, help="fraction off cached input — check pricing")
    ap.add_argument("--gpu-hour", type=float, default=8.0, help="$ per dedicated GPU-hour — check pricing")
    a = ap.parse_args()

    lat = latest("01-latency")
    sweep = latest("03-sweep")
    prefix = latest("06-prefix")
    struct = latest("07-structured")
    evals = latest("09-eval")
    spec = latest("13-spec")

    # --- capacity from the sweep: best concurrency under SLO for the most recent non-mock target
    real = [r for r in sweep if r["target"] != "mock"] or sweep
    under = [r for r in real if float(r["ttft_p95"]) <= a.slo_ms]
    per_replica = max((int(r["conc"]) for r in under), default=None)
    sweep_src = real[-1]["target"] if real else None
    replicas = math.ceil(a.peak_concurrency / per_replica * 1.2) if per_replica else None   # +20% headroom

    # --- prefix caching share
    stable = [r for r in prefix if r["order"] == "stable-first"]
    speedup = stable[-1]["speedup_x"] if stable else None

    # --- serverless monthly cost, with and without caching (assume 90% of input is the shared preamble)
    n = a.tickets_per_month
    cost_in = n * a.in_tokens / 1e6 * a.serverless_in
    cost_out = n * a.out_tokens / 1e6 * a.serverless_out
    cached_share = 0.9
    cost_in_cached = cost_in * (1 - cached_share * a.cached_discount)
    dedicated = replicas * a.gpu_hour * 730 if replicas else None

    # --- quality
    best_eval = max(evals, key=lambda r: float(r["category_%"])) if evals else None
    worst_eval = min(evals, key=lambda r: float(r["category_%"])) if evals else None
    schema = next((r for r in reversed(struct) if r["mode"] == "json_schema"), None)
    prompt_only = next((r for r in reversed(struct) if r["mode"] == "prompt"), None)

    per_ticket = (cost_in_cached + cost_out) / n
    crossover = f"{dedicated / per_ticket:,.0f}" if dedicated else "TODO"
    cap_warning = ("- ⚠ Capacity came from a laptop or mock server. Production GPUs with vLLM/SGLang hold far "
                   "more users per replica; re-run `sweep.py` against the Spark or a Fireworks deployment "
                   "before quoting replica counts.\n") if sweep_src in ("mock", "ollama", "llamacpp", "mlx") else ""

    # (built outside the f-string so this runs on Python 3.10/3.11 too)
    lat_lines = "".join(
        f"- {r['target']} · {r['model']}: TTFT p50 {f(r['ttft_p50_ms'])} ms / p95 {f(r['ttft_p95_ms'])} ms"
        f" · {f(r['tok_per_s'], '{:.0f}')} tok/s per user (prompt ≈{r['prompt_tok']} tok)\n"
        for r in lat[-4:]) or "- TODO (run lesson 01)\n"
    spec_text = ", ".join(f"{r['label']}/{r['traffic']} {f(r['tok_s'])} tok/s" for r in spec[-4:]) or "TODO"

    md = f"""# Sizing memo: {a.customer}

*Generated by `lessons/15-capstone/build_memo.py` from measured results. Prices are inputs; verify them on the pricing page.*

## 1. What they need
- Peak **{a.peak_concurrency} concurrent** agent sessions, **p95 TTFT ≤ {a.slo_ms:.0f} ms**
- **{n:,.0f} tickets/month**, about {a.in_tokens:,} input and {a.out_tokens} output tokens each (the agent preamble dominates)
- Output must be **schema-valid JSON** for the ticketing integration

## 2. Latency profile (lesson 01)
{lat_lines}
## 3. Capacity (lesson 03)
- One replica holds **{per_replica or 'TODO'}** concurrent users within SLO (measured on `{sweep_src or '—'}`)
- Replicas for peak with 20% headroom: **{replicas or 'TODO'}**
{cap_warning}
## 4. Levers that change the bill
| lever | evidence | effect |
|---|---|---|
| Prefix caching: stable preamble first, `user` for affinity | lesson 06: **{f(speedup, '{:.1f}')}×** lower TTFT on warm calls | about 90% of input tokens billed at the cached rate |
| Constrained decoding (`json_schema`) | lesson 07: {f(prompt_only and prompt_only['schema_valid_%'], '{:.0f}')}% → **{f(schema and schema['schema_valid_%'], '{:.0f}')}%** valid | no retry loop, no parser failures |
| Batch API for evals and back-fills | lesson 08 | about 50% off for non-interactive work |
| LoRA fine-tune | lesson 09–11: category accuracy {f(worst_eval and worst_eval['category_%'], '{:.0f}')}% → **{f(best_eval and best_eval['category_%'], '{:.0f}')}%** ({best_eval['candidate'] if best_eval else '—'}) | a smaller model at higher accuracy; needs a dedicated deployment (multi-LoRA shares it) |
| Speculative decoding | lesson 13: {spec_text} | pays on structured output; measure α first |

## 5. Cost options (monthly, rough)
| option | how | $/month |
|---|---|---|
| Serverless, no caching | {n:,.0f} × tokens × list price | **${cost_in + cost_out:,.0f}** |
| Serverless with prefix caching | 90% of input cached at {a.cached_discount:.0%} off | **${cost_in_cached + cost_out:,.0f}** |
| Dedicated, {replicas or '?'} replicas × ${a.gpu_hour}/GPU-h × 730 h | predictable latency; required for the LoRA | **{('$' + format(dedicated, ',.0f')) if dedicated else 'TODO'}** |

**Crossover:** at about **{crossover}** tickets/month, dedicated costs the same as serverless with caching.
Below that, serverless wins. Above it, or when a LoRA or a strict SLO is needed, dedicated wins.

## 6. Recommendation
1. **Now:** serverless with the preamble restructured for caching, plus `json_schema`. It is the cheapest path to production.
2. **In 4–6 weeks,** if accuracy is the blocker: LoRA on a small base, served on dedicated capacity as a multi-LoRA deployment, justified by the eval table.
3. **Always:** nightly evals through the Batch API. Watch p95 TTFT, not averages.

## 7. Risks and what I'd validate next
- Traffic shape: burstiness at peak. Replay a real hour of traffic through `sweep.py`.
- Quality on real tickets, not synthetic ones: 200 hand-labelled examples, with the LLM judge calibrated against them.
- KV headroom if prompts grow (lesson 05): cap the context and consider an FP8 KV cache.
"""
    out = RESULTS / "SIZING_MEMO.md"
    out.write_text(md)
    print(md)
    print(f"\nsaved → {out}")


if __name__ == "__main__":
    main()
